// <auto-generated />
using System;
using Inventory;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Inventory.Migrations
{
    [DbContext(typeof(InventoryContext))]
    partial class InventoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4");

            modelBuilder.Entity("Inventory.Inventar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cena")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DatumZaduzivanja")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdProstorije")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kolicina")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Marka")
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .HasColumnType("TEXT");

                    b.Property<string>("Naziv")
                        .HasColumnType("TEXT");

                    b.Property<string>("UsernameRadnikaKojiJeZaduzio")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Inventar");
                });

            modelBuilder.Entity("Inventory.Prostorija", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Duzina")
                        .HasColumnType("TEXT");

                    b.Property<string>("NazivProstorije")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sirina")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sprat")
                        .HasColumnType("TEXT");

                    b.Property<string>("UsernameSefa")
                        .HasColumnType("TEXT");

                    b.Property<string>("Visina")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Prostorije");
                });

            modelBuilder.Entity("Inventory.Radnik", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JMBG")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("Pol")
                        .HasColumnType("TEXT");

                    b.Property<string>("Prezime")
                        .HasColumnType("TEXT");

                    b.Property<string>("StrucnaSprema")
                        .HasColumnType("TEXT");

                    b.HasKey("Username");

                    b.ToTable("Radnici");
                });
#pragma warning restore 612, 618
        }
    }
}
